
version: '2'
name: keycloak-local-dev
services:
  postgresql:
    image: docker.io/bitnami/postgresql:15
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    networks:
      - keycloak-local-dev-network

  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/realm.json
    command:
      - start-dev
      - --import-realm
    depends_on:
      - postgresql
    ports:
      - "4011:8080"
    volumes:
      - ./../import/themes:/bitnami/keycloak/themes
      - ./../import/realm-config/TSG-realm.json:/opt/keycloak/data/import/realm.json
    networks:
      - keycloak-local-dev-network

networks:
  keycloak-local-dev-network:

volumes:
  postgresql_data:
    driver: local
