service:
  message: "Default Message Prod 01"
management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    readinessState:
      enabled: true
    livenessState:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
  server:
    port: 8081
